
export const allOpportunities: Opportunity[] = [
    // --- CLIENT: AbCS Inc. (id: "123") - 3 Deals ---
    {
        id: "opp-001",
        clientId: "123",
        assignedTo: "user-1",
        createdAt: "01-11-2025 09:00",
        modifiedAt: "05-12-2025 14:20",
        title: "Large Scale Server Implementation",
        stage: "Production",
        probability: 90,
        status: "progress",
        orderAcceptanceDate: "15-11-2025",
        expectedCompletionDate: "20-12-2025",
        completionDate: "",
        actualDuration: "",
        orderTotalAmount: 250000,
        orderTotalCurrency: "AUD",
        prepaymentAmount: 50000,
        prepaymentCurrency: "AUD",
        prepaymentProcent: 20,
        prepaymentDate: "17-11-2025",
        surchargeAmount: 0,
        surchargeCurrency: "AUD",
        surchargeProcent: 0,
        surchargeDate: ""
    },
    {
        id: "opp-002",
        clientId: "123",
        assignedTo: "user-1",
        createdAt: "10-08-2025 10:00",
        modifiedAt: "15-10-2025 11:00",
        title: "Cloud Migration Phase 1",
        stage: "Completed",
        probability: 100,
        status: "success",
        orderAcceptanceDate: "15-08-2025",
        expectedCompletionDate: "10-10-2025",
        completionDate: "12-10-2025",
        actualDuration: "58 days",
        orderTotalAmount: 120000,
        orderTotalCurrency: "AUD",
        prepaymentAmount: 60000,
        prepaymentCurrency: "AUD",
        prepaymentProcent: 50,
        prepaymentDate: "16-08-2025",
        surchargeAmount: 5000,
        surchargeCurrency: "AUD",
        surchargeProcent: 4.1,
        surchargeDate: "05-10-2025"
    },
    {
        id: "opp-003",
        clientId: "123",
        assignedTo: "user-2",
        createdAt: "20-12-2025 16:00",
        modifiedAt: "20-12-2025 16:00",
        title: "Advisory Services Q1",
        stage: "Discovery",
        probability: 20,
        status: "progress",
        orderAcceptanceDate: "",
        expectedCompletionDate: "30-03-2026",
        completionDate: "",
        actualDuration: "",
        orderTotalAmount: 15000,
        orderTotalCurrency: "AUD",
        prepaymentAmount: 0,
        prepaymentCurrency: "AUD",
        prepaymentProcent: 0,
        prepaymentDate: "",
        surchargeAmount: 0,
        surchargeCurrency: "AUD",
        surchargeProcent: 0,
        surchargeDate: ""
    },

    // --- CLIENT: Ababahalamaha publ. (id: "234") - 2 Deals ---
    {
        id: "opp-004",
        clientId: "234",
        assignedTo: "user-3",
        createdAt: "01-12-2025 12:00",
        modifiedAt: "28-12-2025 09:30",
        title: "Winter Catalog Printing",
        stage: "Surcharge",
        probability: 95,
        status: "progress",
        orderAcceptanceDate: "05-12-2025",
        expectedCompletionDate: "15-01-2026",
        completionDate: "",
        actualDuration: "",
        orderTotalAmount: 45000,
        orderTotalCurrency: "UAH",
        prepaymentAmount: 22500,
        prepaymentCurrency: "UAH",
        prepaymentProcent: 50,
        prepaymentDate: "07-12-2025",
        surchargeAmount: 3500,
        surchargeCurrency: "UAH",
        surchargeProcent: 7.7,
        surchargeDate: "27-12-2025"
    },
    {
        id: "opp-005",
        clientId: "234",
        assignedTo: "user-3",
        createdAt: "10-11-2025 08:00",
        modifiedAt: "15-11-2025 14:00",
        title: "Marketing Campaign - Kyiv",
        stage: "Cancelled",
        probability: 0,
        status: "failed",
        orderAcceptanceDate: "",
        expectedCompletionDate: "",
        completionDate: "",
        actualDuration: "",
        orderTotalAmount: 30000,
        orderTotalCurrency: "UAH",
        prepaymentAmount: 0,
        prepaymentCurrency: "UAH",
        prepaymentProcent: 0,
        prepaymentDate: "",
        surchargeAmount: 0,
        surchargeCurrency: "UAH",
        surchargeProcent: 0,
        surchargeDate: ""
    },

    // --- CLIENT: aberero GmbH (id: "345") - 2 Deals ---
    {
        id: "opp-006",
        clientId: "345",
        assignedTo: "user-1",
        createdAt: "05-12-2025 10:00",
        modifiedAt: "06-01-2026 11:00",
        title: "System Integration",
        stage: "Logistics",
        probability: 100,
        status: "progress",
        orderAcceptanceDate: "10-12-2025",
        expectedCompletionDate: "15-01-2026",
        completionDate: "",
        actualDuration: "",
        orderTotalAmount: 88000,
        orderTotalCurrency: "EUR",
        prepaymentAmount: 88000,
        prepaymentCurrency: "EUR",
        prepaymentProcent: 100,
        prepaymentDate: "12-12-2025",
        surchargeAmount: 0,
        surchargeCurrency: "EUR",
        surchargeProcent: 0,
        surchargeDate: ""
    },
    {
        id: "opp-007",
        clientId: "345",
        assignedTo: "user-2",
        createdAt: "20-12-2025 09:00",
        modifiedAt: "02-01-2026 10:00",
        title: "Maintenance Contract 2026",
        stage: "Legal",
        probability: 60,
        status: "progress",
        orderAcceptanceDate: "",
        expectedCompletionDate: "01-02-2026",
        completionDate: "",
        actualDuration: "",
        orderTotalAmount: 12000,
        orderTotalCurrency: "EUR",
        prepaymentAmount: 0,
        prepaymentCurrency: "EUR",
        prepaymentProcent: 0,
        prepaymentDate: "",
        surchargeAmount: 0,
        surchargeCurrency: "EUR",
        surchargeProcent: 0,
        surchargeDate: ""
    },

    // --- CLIENT: Yana Paliy (id: "8910") - 1 Deal ---
    {
        id: "opp-008",
        clientId: "8910",
        assignedTo: "user-4",
        createdAt: "15-12-2025 15:00",
        modifiedAt: "07-01-2026 09:00",
        title: "Private Consultation",
        stage: "Invoicing & Prepayment",
        probability: 80,
        status: "progress",
        orderAcceptanceDate: "03-01-2026",
        expectedCompletionDate: "20-01-2026",
        completionDate: "",
        actualDuration: "",
        orderTotalAmount: 1500,
        orderTotalCurrency: "USD",
        prepaymentAmount: 750,
        prepaymentCurrency: "USD",
        prepaymentProcent: 50,
        prepaymentDate: "",
        surchargeAmount: 0,
        surchargeCurrency: "USD",
        surchargeProcent: 0,
        surchargeDate: ""
    }
];
import type Opportunity from "@lib/types/Opportunity"

export async function GET(_req: Request, { params }: { params: { id: string } }) {
    const { id } = await params;
    const result = allOpportunities.filter((opportunity: Opportunity) => opportunity.clientId === id);

    return Response.json({
        success: result ? true : false,
        opportunity: result
    })
}